#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'aptis/data/speaking';IMG=OUT/'images';IMG.mkdir(parents=True,exist_ok=True)
SVG={
'PARK':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#dff3ff"/><rect y="330" width="800" height="170" fill="#b9e6a2"/><circle cx="100" cy="100" r="45" fill="#ffd66b"/><circle cx="130" cy="235" r="60" fill="#5fa85f"/><circle cx="570" cy="220" r="65" fill="#5fa85f"/><circle cx="330" cy="260" r="22" fill="#284b63"/><circle cx="430" cy="270" r="22" fill="#284b63"/><path d="M250 370 Q400 320 550 370" fill="none" stroke="#d6b37a" stroke-width="28"/></svg>',
'STUDY-ALONE':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#f7f1e8"/><rect x="120" y="320" width="560" height="25" fill="#9b6a43"/><circle cx="390" cy="180" r="45" fill="#f0b58f"/><rect x="355" y="225" width="70" height="110" fill="#4977b8"/><rect x="470" y="245" width="130" height="75" rx="8" fill="#d9e4f2"/></svg>',
'STUDY-GROUP':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#edf7f2"/><ellipse cx="400" cy="350" rx="250" ry="70" fill="#b07b4f"/><circle cx="260" cy="190" r="40" fill="#efb08c"/><circle cx="400" cy="165" r="40" fill="#d79b74"/><circle cx="540" cy="195" r="40" fill="#f2c39f"/><rect x="340" y="300" width="120" height="70" fill="#fff" stroke="#718096" stroke-width="5"/></svg>',
'BUS-STOP':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#dff2ff"/><rect y="350" width="800" height="150" fill="#9aa4ad"/><rect x="90" y="155" width="360" height="190" rx="20" fill="#f0b44f"/><circle cx="170" cy="350" r="42" fill="#333"/><circle cx="370" cy="350" r="42" fill="#333"/><rect x="540" y="120" width="95" height="55" fill="#2f6fb4"/></svg>',
'BICYCLE':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#e5f5ff"/><rect y="370" width="800" height="130" fill="#d5d9dc"/><circle cx="280" cy="360" r="78" fill="none" stroke="#333" stroke-width="14"/><circle cx="520" cy="360" r="78" fill="none" stroke="#333" stroke-width="14"/><path d="M280 360l90-130 80 130H280l70-80h100l70 80" fill="none" stroke="#d84c4c" stroke-width="14"/></svg>',
'TRAIN':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#e7f4ff"/><rect y="380" width="800" height="120" fill="#777"/><rect x="80" y="150" width="640" height="220" rx="45" fill="#d64b4b"/><rect x="130" y="190" width="120" height="80" fill="#bfe6ff"/><rect x="280" y="190" width="120" height="80" fill="#bfe6ff"/><circle cx="210" cy="385" r="35" fill="#222"/><circle cx="590" cy="385" r="35" fill="#222"/></svg>',
'ONLINE-MEETING':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#f2f5fb"/><rect x="120" y="70" width="560" height="330" rx="20" fill="#26384f"/><rect x="155" y="110" width="145" height="105" fill="#9dd2f3"/><rect x="327" y="110" width="145" height="105" fill="#f3c89d"/><rect x="499" y="110" width="145" height="105" fill="#b6dfb3"/></svg>',
'HOME-WORK':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#fff4e6"/><rect x="120" y="310" width="560" height="25" fill="#9b6a43"/><rect x="440" y="210" width="150" height="95" fill="#dbe8f5"/><circle cx="300" cy="190" r="42" fill="#efb18e"/><rect x="265" y="232" width="70" height="100" fill="#4f7aae"/></svg>',
'OFFICE-WORK':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#eef3f7"/><rect x="70" y="120" width="660" height="250" fill="#fff"/><rect x="120" y="300" width="560" height="22" fill="#8c6b50"/><circle cx="220" cy="190" r="35" fill="#e8aa83"/><circle cx="400" cy="180" r="35" fill="#d79b74"/><circle cx="580" cy="195" r="35" fill="#f1bf98"/></svg>',
'CULTURAL-EVENT':'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500"><rect width="800" height="500" fill="#241b3a"/><rect x="170" y="80" width="460" height="230" fill="#6d4bb3"/><circle cx="300" cy="190" r="55" fill="#ffcf5a"/><circle cx="500" cy="190" r="55" fill="#ff7b7b"/><rect y="350" width="800" height="150" fill="#3c3155"/></svg>'}
DATA=[
('ST01','Everyday life and community',['What is one place near your home that you visit regularly? Why do you go there?','Tell me about a person in your community who is helpful.','What do you usually do at weekends?'],'PARK',['Describe the photograph. What is happening in the park?','Tell me about a time when you spent time in a public outdoor place.','Why are green public spaces important in towns and cities?'],('STUDY-ALONE','STUDY-GROUP'),['Describe and compare the two photographs.','What are the advantages of studying alone and studying with other people?','Which way of studying helps people learn more effectively, and why?'],'Think about learning routines. Why can it be difficult to keep a regular routine? What can learners do to stay motivated? How can schools or families support them?'),
('ST02','Travel and daily transport',['How do you usually travel to school or work?','Tell me about a journey you remember clearly.','What kind of transport do you prefer for short trips?'],'BUS-STOP',['Describe the photograph. What can you see at the bus stop?','Tell me about a time when public transport was convenient or inconvenient for you.','What could cities do to make public transport more attractive?'],('BICYCLE','TRAIN'),['Describe and compare the two photographs.','How are travelling by bicycle and travelling by train different?','Which type of transport is likely to become more important in the future, and why?'],'Think about sustainable travel. Why do people continue to use private cars? What changes could encourage greener travel? Who should be responsible for making those changes?'),
('ST03','Work, study and technology',['What piece of technology do you use most often?','Tell me about a useful skill you learned recently.','Where do you prefer to study or work?'],'ONLINE-MEETING',['Describe the photograph. What are the people doing online?','Tell me about a time when technology helped you complete a task.','What problems can happen when people depend too much on technology?'],('HOME-WORK','OFFICE-WORK'),['Describe and compare the two photographs.','What are the benefits of working at home and working in an office?','Which working arrangement will be more common in the future, and why?'],'Think about digital skills. Why do some people find new technology difficult? How can schools and employers help? What digital skills will be most important in the future?'),
('ST04','Health and active lifestyles',['What do you do to stay healthy?','Tell me about a sport or physical activity you enjoy.','What is one healthy habit you would like to improve?'],'PARK',['Describe the photograph. How are the people being active?','Tell me about a time when exercise improved your mood or energy.','Why do some people find it difficult to exercise regularly?'],('BICYCLE','STUDY-GROUP'),['Describe and compare the two photographs.','How are individual exercise and group exercise different?','Which type of activity is more suitable for busy people, and why?'],'Think about public health. What are the main causes of unhealthy lifestyles? What can individuals do to change? What should schools, workplaces and governments do?'),
('ST05','Culture, events and free time',['What kind of music, film or art do you enjoy?','Tell me about an event you attended.','How do you usually spend your free time?'],'CULTURAL-EVENT',['Describe the photograph. What is happening at the event?','Tell me about a cultural event that was memorable for you.','Why are local cultural events valuable for a community?'],('ONLINE-MEETING','CULTURAL-EVENT'),['Describe and compare the two photographs.','How is attending an event online different from attending in person?','Will online cultural events remain popular in the future, and why?'],'Think about free time and culture. Why do some people have very little free time? How can cultural activities improve people’s lives? Should public money support arts and community events?')]
for name,svg in SVG.items():(IMG/f'spk-img-{name.lower()}.svg').write_text(svg,encoding='utf-8')
images=[{'image_id':f'SPK-IMG-{n}','file_path':f'/aptis/data/speaking/images/spk-img-{n.lower()}.svg','alt_text':n.replace('-',' ').title()+' illustration','source':'ForLanguage original vector illustration','license':'CC0-1.0','attribution':'ForLanguage','checksum':'sha256:'+hashlib.sha256(s.encode()).hexdigest(),'status':'PUBLISHED_FINAL'} for n,s in SVG.items()]
topics={}
def topic(name):
 key='SPK-TOP-'+name.upper().replace(' ','-');topics[key]={'topic_id':key,'title_en':name,'title_vi':name,'status':'PUBLISHED_FINAL'};return key
tests=[]
for tid,title,p1,p2img,p2,p3imgs,p3,p4 in DATA:
 ts=[]
 for i,q in enumerate(p1,1):ts.append({'task_id':f'{tid}-P1-Q{i}','part':1,'prompt':q,'preparation_seconds':0,'response_seconds':30,'topic_id':topic('Personal experience'),'topic':'Personal experience','image_ids':[],'status':'PUBLISHED_FINAL','review_note':'Original prompt checked against British Council Part 1 structure.'})
 for i,q in enumerate(p2,1):ts.append({'task_id':f'{tid}-P2-Q{i}','part':2,'prompt':q,'preparation_seconds':0,'response_seconds':45,'topic_id':topic(title),'topic':title,'image_ids':[f'SPK-IMG-{p2img}'],'status':'PUBLISHED_FINAL','review_note':'Original one-image Part 2 sequence: description, experience and general opinion.'})
 for i,q in enumerate(p3,1):ts.append({'task_id':f'{tid}-P3-Q{i}','part':3,'prompt':q,'preparation_seconds':0,'response_seconds':45,'topic_id':topic(title+' comparison'),'topic':title+' comparison','image_ids':[f'SPK-IMG-{x}' for x in p3imgs],'status':'PUBLISHED_FINAL','review_note':'Original two-image Part 3 sequence: comparison and broader opinion/speculation.'})
 ts.append({'task_id':f'{tid}-P4-Q1','part':4,'prompt':p4,'preparation_seconds':60,'response_seconds':120,'topic_id':topic(title+' abstract discussion'),'topic':title+' abstract discussion','image_ids':[],'status':'PUBLISHED_FINAL','review_note':'Original three-question abstract topic with one-minute preparation and two-minute response.'})
 tests.append({'test_id':tid,'title':title,'level':'B2','rubric_id':'SPK-RUB-B2-GENERAL','status':'PUBLISHED_FINAL','version':'2.1.0','source_note':'ForLanguage original practice aligned to public British Council Aptis General Speaking structure and timings; no official prompt or photograph copied.','reviewed_by':['ForLanguage editorial review'],'tasks':ts})
bank={'schema_version':'2.0.0','release':{'release_id':'SPK-2026.08-R2','status':'PUBLISHED_FINAL','created_at':'2026-08-04T04:20:00Z','bank_version':'2.1.0','notes':'Five British Council format-aligned original Speaking tests.'},'topics':list(topics.values()),'rubrics':[{'rubric_id':'SPK-RUB-B2-GENERAL','level':'B2','dimensions':['task_fulfilment','fluency','grammar_accuracy','vocabulary_range','pronunciation','coherence'],'status':'PUBLISHED_FINAL'}],'images':images,'tests':tests}
manifest={'schema_version':'2.0.0','bank_version':'2.1.0','release_id':'SPK-2026.08-R2','status':'PUBLISHED_FINAL','source':'/aptis/data/speaking/bank-v2.json','schema':'/aptis/data/speaking/schema-v2.json','test_count':5,'task_count':50,'topic_count':len(topics),'rubric_count':1,'image_count':len(images),'levels':['B2'],'parts':[1,2,3,4],'compatibility':{'preserved_test_ids':['ST01'],'preserved_task_ids':False,'attempt_contract':'2.0.0','recording_assets':True,'resume':True},'publishing':{'allowed_public_statuses':['PUBLISHED_DEMO','PUBLISHED_FINAL'],'draft_rows_exported':False,'final_release_ready':True,'image_registry_required_for_image_tasks':True,'official_prompt_copying':False,'official_images_copied':False},'source_policy':{'authoritative_format_source':'British Council public Aptis General preparation pages','content_origin':'ForLanguage original','editorial_review':'structured_internal_editorial_review','external_independent_review':False}}
(OUT/'bank-v2.json').write_text(json.dumps(bank,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');(OUT/'manifest-v2.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(f'Generated {len(tests)} tests, {sum(len(t["tasks"]) for t in tests)} tasks, {len(images)} images')
