(() => {
  "use strict";
  const q=s=>document.querySelector(s);const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const fmt=iso=>{try{return iso?new Intl.DateTimeFormat("vi-VN",{dateStyle:"short",timeStyle:"short"}).format(new Date(iso)):"—"}catch{return iso||"—"}};
  const names={core:"Grammar & Vocabulary",reading:"Reading",listening:"Listening",speaking:"Speaking",writing:"Writing",unknown:"Khác"};
  let rows=[],drafts=[];const objectUrls=new Set();
  function downloadJson(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
  function moduleName(v){return names[v]||v||"Khác"}function scoreText(r){if(r.score?.total)return`${r.score.correct}/${r.score.total} (${r.score.percent??"—"}%)`;if(Number.isFinite(Number(r.completed)))return`${r.completed}/${r.total} hoàn thành`;return r.status==="in_progress"?"Đang làm":"Hoàn thành"}
  function filteredRows(){const m=q("#moduleFilter").value,t=q("#historySearch").value.trim().toLowerCase();return rows.filter(r=>(m==="all"||r.module===m)&&(!t||JSON.stringify(r).toLowerCase().includes(t)))}
  function actions(r){let x=`<button data-review="${esc(r.attempt_id)}">Review</button>`;if(r.status==="in_progress")x+=`<button data-resume="${esc(r.attempt_id)}">Tiếp tục</button>`;if(r.module==="writing")x+=`<button data-restore="${esc(r.attempt_id)}">Tạo draft</button>`;if(r.module==="listening"&&(r.responses||[]).some(a=>a.is_correct===false))x+=`<button data-retry-wrong="${esc(r.attempt_id)}">Làm lại câu sai</button>`;return x+`<button data-json="${esc(r.attempt_id)}">JSON</button><button data-delete="${esc(r.attempt_id)}">Xóa</button>`}
  async function updateSummary(){const s=await AptisAttemptStore.getStorageSummary();q("#historySummary").innerHTML=`<strong>${rows.length} lượt làm</strong><br><span>${s.assets} recordings · ${s.drafts} drafts</span>`;q("#storageSummary").innerHTML=`<strong>Contract ${AptisAttemptStore.contractVersion}</strong><span>IndexedDB v2 · local-first</span><a href="/aptis/contracts/attempt-contract-v2.json">Xem contract</a>`}
  function render(){const visible=filteredRows();q("#historyRows").innerHTML=visible.length?visible.map(r=>`<tr><td>${esc(fmt(r.submitted_at||r.updated_at))}</td><td><span class="badge">${esc(moduleName(r.module))}</span></td><td><strong>${esc(r.mode_label||r.test_id||"Bài luyện")}</strong><br><small>${esc(r.test_id||r.attempt_id)}</small></td><td>${esc(scoreText(r))}</td><td>${r.migrated_from_legacy?"Migrated v5":"IndexedDB v2"}</td><td><div class="row-actions">${actions(r)}</div></td></tr>`).join(""):`<tr><td class="empty" colspan="6">Không có kết quả phù hợp.</td></tr>`;bind();renderDrafts();updateSummary()}
  function renderDrafts(){let host=q("#draftManager");if(!host){host=document.createElement("section");host.id="draftManager";host.className="draft-manager";q(".history-table-wrap").after(host)}host.innerHTML=`<div class="draft-head"><div><p class="eyebrow">DRAFT MANAGER</p><h2>Draft đang lưu</h2></div><span>${drafts.length} drafts</span></div>${drafts.length?drafts.map(d=>`<article><div><strong>${esc(d.test_id)} · ${esc(d.mode||"full")}</strong><small>${esc(fmt(d.updated_at))}</small></div><div class="row-actions"><button data-open-draft="${esc(d.draft_id)}">Mở</button><button data-download-draft="${esc(d.draft_id)}">JSON</button><button data-delete-draft="${esc(d.draft_id)}">Xóa</button></div></article>`).join(""):`<p class="empty-card">Chưa có draft.</p>`;document.querySelectorAll("[data-open-draft]").forEach(b=>b.onclick=()=>openDraft(b.dataset.openDraft));document.querySelectorAll("[data-download-draft]").forEach(b=>b.onclick=()=>{const d=drafts.find(x=>x.draft_id===b.dataset.downloadDraft);if(d)downloadJson(d,`${d.draft_id}.json`)});document.querySelectorAll("[data-delete-draft]").forEach(b=>b.onclick=async()=>{if(confirm("Xóa draft này?")){await AptisAttemptStore.deleteDraft(b.dataset.deleteDraft);await load()}})}
  function bind(){document.querySelectorAll("[data-review]").forEach(b=>b.onclick=()=>openReview(b.dataset.review));document.querySelectorAll("[data-json]").forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.attempt_id===b.dataset.json);if(r)downloadJson(r,`aptis-${r.module}-${r.attempt_id}.json`)});document.querySelectorAll("[data-delete]").forEach(b=>b.onclick=async()=>{if(confirm("Xóa attempt và assets liên quan?")){await AptisAttemptStore.deleteAttempt(b.dataset.delete);await load()}});document.querySelectorAll("[data-restore]").forEach(b=>b.onclick=()=>restoreWriting(b.dataset.restore));document.querySelectorAll("[data-retry-wrong]").forEach(b=>b.onclick=()=>retryWrong(b.dataset.retryWrong));document.querySelectorAll("[data-resume]").forEach(b=>b.onclick=()=>resumeAttempt(b.dataset.resume))}
  async function restoreWriting(id){const r=rows.find(x=>x.attempt_id===id);const draft={draft_id:`writing:${r.test_id}:${r.mode||"full"}`,module:"writing",test_id:r.test_id,mode:r.mode||"full",title:r.mode_label,responses:r.responses||[],source_attempt_id:id,status:"in_progress"};await AptisAttemptStore.saveDraft(draft);location.href=`/aptis/writing/?draft=${encodeURIComponent(draft.draft_id)}`}
  function retryWrong(id){const r=rows.find(x=>x.attempt_id===id);const wrong=(r.responses||[]).filter(x=>x.is_correct===false).map(x=>x.item_id);sessionStorage.setItem("aptisListeningRetryWrong",JSON.stringify({test_id:r.test_id,item_ids:wrong,source_attempt_id:id}));location.href="/aptis/listening/?retry=wrong"}
  function resumeAttempt(id){const r=rows.find(x=>x.attempt_id===id);if(r.module==="writing")return restoreWriting(id);sessionStorage.setItem("aptisResumeAttempt",JSON.stringify(r));location.href=`/aptis/${r.module}/?resume=${encodeURIComponent(id)}`}
  function responseCard(x,i){return`<article class="review-card ${x.is_correct===true?"correct":x.is_correct===false?"wrong":""}"><small>${esc(x.item_id||x.task_id||`#${i+1}`)}</small><h3>${esc(x.question||x.prompt||"Response")}</h3>${x.text?`<p class="response-text">${esc(x.text)}</p>`:""}${x.user_label||x.correct_label?`<p>Bạn chọn: <strong>${esc(x.user_label||"Chưa trả lời")}</strong> · Đáp án: <strong>${esc(x.correct_label||"—")}</strong></p>`:""}${x.explanation_vi?`<p>${esc(x.explanation_vi)}</p>`:""}</article>`}
  async function openReview(id){objectUrls.forEach(URL.revokeObjectURL);objectUrls.clear();const r=rows.find(x=>x.attempt_id===id);q("#reviewTitle").textContent=`${moduleName(r.module)} · ${r.test_id||r.mode_label}`;let body=`<section class="attempt-meta"><span>${esc(r.attempt_id)}</span><span>${esc(fmt(r.submitted_at||r.updated_at))}</span><span>${esc(scoreText(r))}</span></section>`;if(r.module==="speaking"){const assets=await AptisAttemptStore.listAssets(id);body+=assets.length?assets.map(a=>{const u=URL.createObjectURL(a.blob);objectUrls.add(u);return`<article class="review-card"><h3>${esc(a.task_id||a.asset_id)}</h3><audio controls src="${u}"></audio><a href="${u}" download="${esc(a.task_id||a.asset_id)}.webm">Tải recording</a></article>`}).join(""):`<p class="empty-card">Không có recording.</p>`}else if(r.module==="writing")body+=(r.responses||[]).map(t=>`<article class="review-card"><h3>Part ${esc(t.part||"")}</h3>${(t.responses||[]).map(x=>`<div class="writing-response"><p>${esc(x.text||"")}</p><small>${x.word_count||0} words</small></div>`).join("")}</article>`).join("");else body+=(r.responses||[]).map(responseCard).join("")||`<p class="empty-card">Chưa có response chi tiết.</p>`;q("#reviewContent").innerHTML=body;q("#reviewDialog").showModal()}
  function openDraft(id){location.href=`/aptis/writing/?draft=${encodeURIComponent(id)}`}
  async function load(){await AptisAttemptStore.migrateLegacyHistory();[rows,drafts]=await Promise.all([AptisAttemptStore.listAttempts(),AptisAttemptStore.listDrafts()]);render()}
  q("#moduleFilter").onchange=render;q("#historySearch").oninput=render;q("#refreshHistory").onclick=load;q("#exportHistory").onclick=async()=>downloadJson(await AptisAttemptStore.exportBackup(),`aptis-backup-${new Date().toISOString().slice(0,10)}.json`);q("#importHistory").onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const r=await AptisAttemptStore.importBackup(JSON.parse(await f.text()));alert(`Đã import ${r.attempts} attempts và ${r.drafts} drafts.`);await load()}catch(err){alert(err.message)}e.target.value=""};q("#reviewDialog").addEventListener("close",()=>{objectUrls.forEach(URL.revokeObjectURL);objectUrls.clear()});load().catch(console.error);
})();
