(() => {
  "use strict";
  const $=id=>document.getElementById(id);
  const labels="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
  const state={bank:null,mode:null,items:[],answers:{},startedAt:null,timer:null,seconds:0,lastWrong:[]};
  const escapeHtml=value=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[c]);
  const shuffle=rows=>{const a=[...rows];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
  const sample=(rows,n)=>shuffle(rows).slice(0,Math.min(n,rows.length));
  function stopTimer(){if(state.timer)clearInterval(state.timer);state.timer=null;}
  function renderTimer(){const m=Math.floor(state.seconds/60),s=state.seconds%60;$("timerText").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;}
  function startTimer(){stopTimer();state.seconds=0;renderTimer();state.timer=setInterval(()=>{state.seconds+=1;renderTimer();},1000);}
  function strategy(mode){return({grammar15:"Làm chậm, xác định meaning/timeline trước khi nhìn đáp án.",grammar30:"Giải thích vì sao hai distractor sai sau khi nộp.",vocab10:"Học theo cụm và register, không dịch từng từ rời.",cohesion:"Đánh dấu noun→pronoun, cause→result và time markers trước khi xếp.",opinion:"Gạch paraphrase trong statement rồi tìm ý tương đương, không tìm từ giống hệt."})[mode]||"Chọn một chế độ để bắt đầu.";}
  function setVisibility(quiz,result){$("quizSection").hidden=!quiz;$("resultSection").hidden=!result;}
  function modeTitle(mode){return({grammar15:"Grammar Focus · 15 câu",grammar30:"Grammar Master · 30 câu",vocab10:"Vocabulary High-Yield · 10 câu",cohesion:"Reading Part 2 · Text Cohesion",opinion:"Reading Part 3 · Opinion Matching"})[mode]||mode;}
  function makeGrammar(mode){const cluster=$("clusterSelect").value,pool=cluster==="all"?state.bank.grammar:state.bank.grammar.filter(q=>q.cluster===cluster);const n=mode==="grammar30"?30:15;return sample(pool,n).map(q=>({kind:"mcq",...q}));}
  function makeVocab(){return shuffle(state.bank.vocabulary).map(q=>({kind:"mcq",...q}));}
  function makeCohesion(){const set=sample(state.bank.reading_part2,1)[0];return[{kind:"cohesion",...set}];}
  function makeOpinion(){const set=sample(state.bank.reading_part3,1)[0];return[{kind:"opinion",...set}];}
  function start(mode,override=null){
    state.mode=mode;state.answers={};state.startedAt=new Date().toISOString();state.lastWrong=[];
    if(override)state.items=override;else if(mode.startsWith("grammar"))state.items=makeGrammar(mode);else if(mode==="vocab10")state.items=makeVocab();else if(mode==="cohesion")state.items=makeCohesion();else state.items=makeOpinion();
    if(!state.items.length){alert("Không có đủ câu cho bộ lọc này.");return;}
    $("strategyText").textContent=strategy(mode);$("quizLabel").textContent="HIGH-YIELD PRACTICE";$("quizTitle").textContent=modeTitle(mode);setVisibility(true,false);renderQuiz();startTimer();window.scrollTo({top:$("quizSection").offsetTop-80,behavior:"smooth"});
  }
  function renderMcq(item,index){return`<article class="question-card"><div class="question-meta"><span class="tag">${escapeHtml(item.topic)}</span><span class="tag">${escapeHtml(item.level)}</span><span class="tag">${escapeHtml(item.id)}</span></div><h3>${index+1}. ${escapeHtml(item.question)}</h3><div class="option-list">${item.options.map((opt,i)=>{const label=labels[i];return`<label><input type="radio" name="${item.id}" value="${label}" ${state.answers[item.id]===label?"checked":""}><b>${label}.</b><span>${escapeHtml(opt)}</span></label>`}).join("")}</div></article>`;}
  function renderCohesion(set){return`<article class="reading-set"><div class="question-meta"><span class="tag">Reading Part 2</span><span class="tag">${escapeHtml(set.level)}</span><span class="tag">${escapeHtml(set.set_id)}</span></div><h3>${escapeHtml(set.title)}</h3><div class="fixed-first"><b>Câu đầu cố định:</b> ${escapeHtml(set.fixed_first)}</div><div class="sentence-bank">${Object.entries(set.sentences).map(([label,text])=>`<div><b>${label}</b><span>${escapeHtml(text)}</span></div>`).join("")}</div><div class="order-grid">${[0,1,2,3,4].map(pos=>`<label class="order-row"><strong>Vị trí ${pos+2}</strong><select data-order="${pos}"><option value="">— Chọn câu —</option>${Object.keys(set.sentences).map(label=>`<option value="${label}" ${state.answers[`${set.set_id}-${pos}`]===label?"selected":""}>${label}</option>`).join("")}</select></label>`).join("")}</div></article>`;}
  function renderOpinion(set){return`<article class="reading-set"><div class="question-meta"><span class="tag">Reading Part 3</span><span class="tag">${escapeHtml(set.level)}</span><span class="tag">${escapeHtml(set.set_id)}</span></div><h3>${escapeHtml(set.title)}</h3><div class="people-grid">${set.people.map(p=>`<article><h4>${p.label} · ${escapeHtml(p.name)}</h4><p>${escapeHtml(p.text)}</p></article>`).join("")}</div><div class="match-list">${set.statements.map((q,i)=>`<label class="match-row"><span><b>${i+1}.</b> ${escapeHtml(q.text)}</span><select data-match="${q.id}"><option value="">— Chọn —</option>${set.people.map(p=>`<option value="${p.label}" ${state.answers[q.id]===p.label?"selected":""}>${p.label} · ${escapeHtml(p.name)}</option>`).join("")}</select></label>`).join("")}</div></article>`;}
  function totalQuestions(){if(state.items[0]?.kind==="cohesion")return 5;if(state.items[0]?.kind==="opinion")return state.items[0].statements.length;return state.items.length;}
  function answeredCount(){if(state.items[0]?.kind==="cohesion")return [0,1,2,3,4].filter(i=>state.answers[`${state.items[0].set_id}-${i}`]).length;if(state.items[0]?.kind==="opinion")return state.items[0].statements.filter(q=>state.answers[q.id]).length;return state.items.filter(q=>state.answers[q.id]).length;}
  function updateProgress(){$("progressText").textContent=`${answeredCount()}/${totalQuestions()} đã trả lời`;}
  function renderQuiz(){const kind=state.items[0]?.kind;$("quizHost").innerHTML=kind==="cohesion"?renderCohesion(state.items[0]):kind==="opinion"?renderOpinion(state.items[0]):state.items.map(renderMcq).join("");
    document.querySelectorAll('#quizHost input[type="radio"]').forEach(input=>input.addEventListener("change",e=>{state.answers[e.target.name]=e.target.value;updateProgress();}));
    document.querySelectorAll("[data-order]").forEach(select=>select.addEventListener("change",e=>{const set=state.items[0],pos=Number(e.target.dataset.order);state.answers[`${set.set_id}-${pos}`]=e.target.value;refreshUniqueOrders();updateProgress();}));
    document.querySelectorAll("[data-match]").forEach(select=>select.addEventListener("change",e=>{state.answers[e.target.dataset.match]=e.target.value;updateProgress();}));refreshUniqueOrders();updateProgress();}
  function refreshUniqueOrders(){const selects=[...document.querySelectorAll("[data-order]")];if(!selects.length)return;const chosen=selects.map(s=>s.value).filter(Boolean);selects.forEach(s=>[...s.options].forEach(o=>{o.disabled=!!o.value&&o.value!==s.value&&chosen.includes(o.value);}));}
  function grade(){const kind=state.items[0]?.kind;let rows=[];
    if(kind==="cohesion"){const set=state.items[0];rows=set.answer_order.map((correct,pos)=>{const id=`${set.set_id}-${pos}`,user=state.answers[id]||null;return{id,kind,question:`Vị trí ${pos+2}`,user,correct,is_correct:user===correct,explanation_vi:set.explanation_vi,set};});}
    else if(kind==="opinion"){const set=state.items[0];rows=set.statements.map(q=>({id:q.id,kind,question:q.text,user:state.answers[q.id]||null,correct:q.answer,is_correct:state.answers[q.id]===q.answer,explanation_vi:`Paraphrase: ${q.paraphrase}`,set}));}
    else rows=state.items.map(q=>({id:q.id,kind:"mcq",question:q.question,user:state.answers[q.id]||null,correct:q.answer,is_correct:state.answers[q.id]===q.answer,explanation_vi:q.explanation_vi,item:q}));return rows;}
  function answerText(row,label){if(!label)return"Chưa trả lời";if(row.kind==="mcq"){const idx=labels.indexOf(label);return`${label}. ${row.item.options[idx]||""}`;}if(row.kind==="opinion"){const p=row.set.people.find(x=>x.label===label);return`${label}${p?` · ${p.name}`:""}`;}return label;}
  async function saveAttempt(rows,correct){if(!window.AptisAttemptStore)return;const isReading=["cohesion","opinion"].includes(state.mode),id=`HY-${state.mode}-${Date.now()}`;await AptisAttemptStore.saveAttempt({attempt_id:id,result_id:id,module:isReading?"reading":"core",test_id:state.items[0]?.set_id||state.bank.release.release_id,mode:`high_yield_${state.mode}`,mode_label:modeTitle(state.mode),status:"completed",started_at:state.startedAt,submitted_at:new Date().toISOString(),duration_seconds:state.seconds,score:{correct,total:rows.length,percent:Math.round(correct*100/rows.length),blank:rows.filter(r=>!r.user).length},answers:rows.map(r=>({item_id:r.id,question:r.question,user_label:r.user,correct_label:r.correct,is_correct:r.is_correct,explanation_vi:r.explanation_vi})),source:"forlanguage-high-yield-v1",bank_release:state.bank.release.release_id});}
  async function submit(){stopTimer();const rows=grade(),correct=rows.filter(r=>r.is_correct).length,percent=Math.round(correct*100/rows.length);state.lastWrong=rows.filter(r=>!r.is_correct);$("resultScore").textContent=`${correct}/${rows.length}`;$("resultPercent").textContent=`${percent}%`;$("resultMessage").textContent=percent>=85?"Rất ổn. Hãy giải thích lại các distractor để khóa kiến thức.":percent>=70?"Đã khá hơn; review kỹ các lỗi có cùng signal.":"Nên làm lại cùng dạng sau khi đọc phần giải thích.";$("reviewHost").innerHTML=rows.map(row=>`<article class="review-item ${row.is_correct?"correct":"wrong"}"><strong>${escapeHtml(row.id)} · ${row.is_correct?"Đúng":"Cần xem lại"}</strong><p>${escapeHtml(row.question)}</p><p>Bạn chọn: <b>${escapeHtml(answerText(row,row.user))}</b><br>Đáp án: <b>${escapeHtml(answerText(row,row.correct))}</b></p><p class="explain">${escapeHtml(row.explanation_vi)}</p></article>`).join("");$("retryWrong").disabled=!state.lastWrong.length;setVisibility(false,true);try{await saveAttempt(rows,correct);}catch(error){console.error("Unable to save targeted attempt",error);}window.scrollTo({top:$("resultSection").offsetTop-80,behavior:"smooth"});}
  function retryWrong(){if(!state.lastWrong.length)return;const kind=state.items[0]?.kind;if(kind==="mcq"||!kind){const ids=new Set(state.lastWrong.map(r=>r.id));start(state.mode,state.items.filter(q=>ids.has(q.id)));return;}start(state.mode,state.items);}
  async function load(){const response=await fetch("/aptis/data/targeted/high-yield-v1.json",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);state.bank=await response.json();$("bankSummary").textContent=`${state.bank.grammar.length} Grammar · ${state.bank.vocabulary.length} Vocabulary · ${state.bank.reading_part2.length} P2 sets · ${state.bank.reading_part3.length} P3 sets`;document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>start(button.dataset.mode)));}
  $("clusterSelect").addEventListener("change",()=>{$("strategyText").textContent=$("clusterSelect").value==="all"?"Chọn Grammar Focus để lấy mẫu cân bằng nhiều nhóm.":"Bộ Grammar Focus sẽ chỉ lấy câu trong nhóm này.";});$("submitQuiz").addEventListener("click",()=>submit().catch(error=>alert(error.message)));$("cancelQuiz").addEventListener("click",()=>{stopTimer();setVisibility(false,false);window.scrollTo({top:0,behavior:"smooth"});});$("backModes").addEventListener("click",()=>{setVisibility(false,false);window.scrollTo({top:0,behavior:"smooth"});});$("retryWrong").addEventListener("click",retryWrong);window.addEventListener("beforeunload",stopTimer);load().catch(error=>{$("bankSummary").textContent=`Không tải được bank: ${error.message}`;console.error(error);});
})();
