(() => {
  "use strict";
  let bank=null,test=null,index=0,stream=null,recorder=null,chunks=[],timer=null,sessionAttemptId=null,activeUrl=null;
  const $=id=>document.getElementById(id);const state={recordings:{},notes:{},started_at:null};
  async function loadTest(){const r=await fetch("/aptis/data/speaking/bank-v2.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);bank=await r.json();if(bank.schema_version!=="2.0.0")throw new Error("Unsupported Speaking bank schema");test=bank.tests[0];}
  async function mic(){if(!navigator.mediaDevices?.getUserMedia)throw new Error("Trình duyệt không hỗ trợ microphone.");stream ||= await navigator.mediaDevices.getUserMedia({audio:true});$("permissionState").textContent="Đã cấp quyền";$("requestMic").textContent="Microphone sẵn sàng";}
  function clearTimer(){if(timer)clearInterval(timer);timer=null;}
  function countdown(seconds,label,done){clearTimer();let left=seconds;$("timerLabel").textContent=`${label}: ${left}s`;timer=setInterval(()=>{left-=1;$("timerLabel").textContent=`${label}: ${Math.max(left,0)}s`;if(left<=0){clearTimer();done();}},1000);}
  const ext=m=>m?.includes("mp4")?"m4a":m?.includes("ogg")?"ogg":"webm";
  function render(){const task=test.tasks[index],recording=state.recordings[task.task_id];if(activeUrl)URL.revokeObjectURL(activeUrl);activeUrl=null;$("taskProgress").textContent=`Câu ${index+1}/${test.tasks.length}`;$("partLabel").textContent=`PART ${task.part}`;$("promptText").textContent=task.prompt;$("topicText").textContent=`Chủ đề: ${task.topic} · Chuẩn bị ${task.preparation_seconds}s · Trả lời ${task.response_seconds}s`;$("selfNote").value=state.notes[task.task_id]||"";$("prevTask").disabled=index===0;$("taskHost").hidden=false;$("recordBtn").disabled=false;$("stopBtn").disabled=true;$("retryBtn").disabled=!recording;$("playback").hidden=!recording;$("downloadRecording").hidden=!recording;$("timerLabel").textContent=recording?"Đã khôi phục recording":"Sẵn sàng";if(recording){activeUrl=URL.createObjectURL(recording.blob);$("playback").src=activeUrl;$("downloadRecording").href=activeUrl;$("downloadRecording").download=`aptis-${test.test_id}-${task.task_id}.${ext(recording.mime_type)}`;}}
  async function startRecording(){await mic();if(recorder?.state==="recording")return;chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=async()=>{const task=test.tasks[index],blob=new Blob(chunks,{type:recorder.mimeType||"audio/webm"});state.recordings[task.task_id]={blob,mime_type:blob.type,duration_seconds:task.response_seconds,created_at:new Date().toISOString()};await saveCurrent();render();};recorder.start(500);$("recordBtn").disabled=true;$("stopBtn").disabled=false;countdown(test.tasks[index].response_seconds,"Đang ghi",()=>{if(recorder?.state==="recording")recorder.stop();});}
  async function saveAttemptProgress(status="in_progress"){const responses=test.tasks.map(t=>({task_id:t.task_id,part:t.part,prompt:t.prompt,topic_id:t.topic_id,image_ids:t.image_ids||[],note:state.notes[t.task_id]||"",recorded:Boolean(state.recordings[t.task_id]),mime_type:state.recordings[t.task_id]?.mime_type||null}));await AptisAttemptStore.saveAttempt({attempt_id:sessionAttemptId,result_id:sessionAttemptId,module:"speaking",test_id:test.test_id,mode:"full_demo",mode_label:test.title,status,started_at:state.started_at,submitted_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString(),responses,completed:responses.filter(r=>r.recorded).length,total:responses.length,score:null,rubric_id:test.rubric_id,bank_release:bank.release?.release_id,source:"forlanguage-speaking-v2"});}
  async function saveCurrent(){if(!test||!sessionAttemptId)return;const task=test.tasks[index];state.notes[task.task_id]=$("selfNote").value;const recording=state.recordings[task.task_id];if(recording)await AptisAttemptStore.saveAsset({asset_id:`${sessionAttemptId}-${task.task_id}`,attempt_id:sessionAttemptId,kind:"speaking_recording",task_id:task.task_id,part:task.part,blob:recording.blob,mime_type:recording.mime_type,duration_seconds:recording.duration_seconds,created_at:recording.created_at});await saveAttemptProgress("in_progress");}
  async function resume(){let payload=null;try{payload=JSON.parse(sessionStorage.getItem("aptisResumeAttempt")||"null");}catch{}const id=new URLSearchParams(location.search).get("resume")||payload?.attempt_id;if(!id)return false;const attempt=await AptisAttemptStore.getAttempt(id);if(!attempt||attempt.module!=="speaking")return false;sessionAttemptId=id;state.started_at=attempt.started_at||new Date().toISOString();(attempt.responses||attempt.answers||[]).forEach(r=>state.notes[r.task_id]=r.note||"");for(const asset of await AptisAttemptStore.listAssets(id)){if(asset.blob)state.recordings[asset.task_id]={blob:asset.blob,mime_type:asset.mime_type,duration_seconds:asset.duration_seconds,created_at:asset.created_at};}index=Math.max(0,test.tasks.findIndex(t=>!state.recordings[t.task_id]));if(index<0)index=0;sessionStorage.removeItem("aptisResumeAttempt");render();$("downloadAll").disabled=false;return true;}
  async function finalize(){await saveCurrent();await saveAttemptProgress("completed");alert("Đã hoàn thành và lưu phiên Speaking.");location.href="/aptis/history/";}
  $("requestMic").onclick=()=>mic().catch(e=>alert(e.message));$("startPractice").onclick=async()=>{sessionAttemptId=`SPK-${test.test_id}-${Date.now()}`;state.started_at=new Date().toISOString();index=0;await saveAttemptProgress("in_progress");render();};$("prepareBtn").onclick=()=>countdown(test.tasks[index].preparation_seconds,"Chuẩn bị",()=>startRecording().catch(e=>alert(e.message)));$("recordBtn").onclick=()=>startRecording().catch(e=>alert(e.message));$("stopBtn").onclick=()=>{clearTimer();if(recorder?.state==="recording")recorder.stop();};$("retryBtn").onclick=()=>{state.recordings[test.tasks[index].task_id]=null;render();};$("prevTask").onclick=async()=>{await saveCurrent();if(index>0){index-=1;render();}};$("saveNext").onclick=async()=>{await saveCurrent();if(index<test.tasks.length-1){index+=1;render();}else await finalize();};$("downloadAll").onclick=()=>{const data={schema_version:"2.0.0",bank_release:bank.release?.release_id,attempt_id:sessionAttemptId,test_id:test.test_id,responses:test.tasks.map(t=>({task_id:t.task_id,note:state.notes[t.task_id]||"",recorded:Boolean(state.recordings[t.task_id])}))};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`aptis-speaking-${sessionAttemptId}.json`;a.click();};
  window.addEventListener("beforeunload",()=>{clearTimer();stream?.getTracks().forEach(t=>t.stop());if(activeUrl)URL.revokeObjectURL(activeUrl);});
  loadTest().then(resume).catch(console.error);
})();
