(() => {
  "use strict";
  let bank=null,test=null,index=0,timer=null,sessionAttemptId=null,activeUrl=null;
  const $=id=>document.getElementById(id);const state={recordings:{},notes:{},started_at:null};
  const media=new AptisMediaRecorderService({minDurationMs:800});
  async function loadTest(){const r=await fetch("/aptis/data/speaking/bank-v2.json",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);bank=await r.json();if(bank.schema_version!=="2.0.0")throw new Error("Unsupported Speaking bank schema");test=bank.tests[0];}
  async function mic(){await media.requestMicrophone();$("permissionState").textContent="Đã cấp quyền";$("requestMic").textContent="Microphone sẵn sàng";$("micHint").textContent="Hãy nói thử và kiểm tra mức tín hiệu.";}
  media.onLevel(level=>{const meter=$("micLevel");if(meter)meter.value=level;const hint=$("micHint");if(hint&&media.stream?.active)hint.textContent=level<0.04?"Tín hiệu rất nhỏ — hãy nói gần microphone hơn.":level>0.85?"Tín hiệu quá lớn — hãy lùi xa microphone một chút.":"Mức tín hiệu phù hợp.";});
  function clearTimer(){if(timer)clearInterval(timer);timer=null;}
  function countdown(seconds,label,done){clearTimer();let left=seconds;$("timerLabel").textContent=`${label}: ${left}s`;timer=setInterval(()=>{left-=1;$("timerLabel").textContent=`${label}: ${Math.max(left,0)}s`;if(left<=0){clearTimer();done();}},1000);}
  const ext=m=>m?.includes("mp4")?"m4a":m?.includes("ogg")?"ogg":"webm";
  function render(){const task=test.tasks[index],recording=state.recordings[task.task_id];if(activeUrl)URL.revokeObjectURL(activeUrl);activeUrl=null;$("taskProgress").textContent=`Câu ${index+1}/${test.tasks.length}`;$("partLabel").textContent=`PART ${task.part}`;$("promptText").textContent=task.prompt;$("topicText").textContent=`Chủ đề: ${task.topic} · Chuẩn bị ${task.preparation_seconds}s · Trả lời ${task.response_seconds}s`;$("selfNote").value=state.notes[task.task_id]||"";$("prevTask").disabled=index===0;$("taskHost").hidden=false;$("recordBtn").disabled=false;$("stopBtn").disabled=true;$("retryBtn").disabled=!recording;$("playback").hidden=!recording;$("downloadRecording").hidden=!recording;$("timerLabel").textContent=recording?"Đã khôi phục recording":"Sẵn sàng";$("recordingInfo").textContent=recording?`${recording.duration_seconds}s · ${Math.round((recording.size_bytes||recording.blob.size)/1024)} KB`:"";if(recording){activeUrl=URL.createObjectURL(recording.blob);$("playback").src=activeUrl;$("downloadRecording").href=activeUrl;$("downloadRecording").download=`aptis-${test.test_id}-${task.task_id}.${ext(recording.mime_type)}`;}}
  async function startRecording(){await mic();if(media.recorder?.state==="recording")return;await media.start();$("recordBtn").disabled=true;$("stopBtn").disabled=false;$("recordingInfo").textContent="Đang ghi âm…";countdown(test.tasks[index].response_seconds,"Đang ghi",()=>stopRecording().catch(e=>alert(e.message)));}
  async function stopRecording(){clearTimer();if(media.recorder?.state!=="recording")return;const task=test.tasks[index],recording=await media.stop();$("recordBtn").disabled=false;$("stopBtn").disabled=true;if(recording.empty){$("recordingInfo").textContent=recording.warning;alert(recording.warning);return;}state.recordings[task.task_id]=recording;await saveCurrent();render();}
  async function saveAttemptProgress(status="in_progress"){const responses=test.tasks.map(t=>({task_id:t.task_id,part:t.part,prompt:t.prompt,topic_id:t.topic_id,image_ids:t.image_ids||[],note:state.notes[t.task_id]||"",recorded:Boolean(state.recordings[t.task_id]),mime_type:state.recordings[t.task_id]?.mime_type||null,duration_seconds:state.recordings[t.task_id]?.duration_seconds||null,size_bytes:state.recordings[t.task_id]?.size_bytes||null}));await AptisAttemptStore.saveAttempt({attempt_id:sessionAttemptId,result_id:sessionAttemptId,module:"speaking",test_id:test.test_id,mode:"full_demo",mode_label:test.title,status,started_at:state.started_at,submitted_at:status==="completed"?new Date().toISOString():null,updated_at:new Date().toISOString(),responses,completed:responses.filter(r=>r.recorded).length,total:responses.length,score:null,rubric_id:test.rubric_id,bank_release:bank.release?.release_id,source:"forlanguage-speaking-v2.1"});}
  async function saveCurrent(){if(!test||!sessionAttemptId)return;const task=test.tasks[index];state.notes[task.task_id]=$("selfNote").value;const recording=state.recordings[task.task_id];if(recording)await AptisAttemptStore.saveAsset({asset_id:`${sessionAttemptId}-${task.task_id}`,attempt_id:sessionAttemptId,kind:"speaking_recording",task_id:task.task_id,part:task.part,blob:recording.blob,mime_type:recording.mime_type,duration_seconds:recording.duration_seconds,size_bytes:recording.size_bytes,created_at:recording.created_at});await saveAttemptProgress("in_progress");}
  async function resume(){let payload=null;try{payload=JSON.parse(sessionStorage.getItem("aptisResumeAttempt")||"null");}catch{}const id=new URLSearchParams(location.search).get("resume")||payload?.attempt_id;if(!id)return false;const attempt=await AptisAttemptStore.getAttempt(id);if(!attempt||attempt.module!=="speaking")return false;sessionAttemptId=id;state.started_at=attempt.started_at||new Date().toISOString();(attempt.responses||attempt.answers||[]).forEach(r=>state.notes[r.task_id]=r.note||"");for(const asset of await AptisAttemptStore.listAssets(id)){if(asset.blob)state.recordings[asset.task_id]={blob:asset.blob,mime_type:asset.mime_type,duration_seconds:asset.duration_seconds,size_bytes:asset.size_bytes||asset.blob.size,created_at:asset.created_at};}index=Math.max(0,test.tasks.findIndex(t=>!state.recordings[t.task_id]));if(index<0)index=0;sessionStorage.removeItem("aptisResumeAttempt");render();$("downloadAll").disabled=false;return true;}
  async function finalize(){await saveCurrent();await saveAttemptProgress("completed");media.stopTracks();alert("Đã hoàn thành và lưu phiên Speaking.");location.href="/aptis/history/";}
  $("requestMic").onclick=()=>mic().catch(e=>{$("permissionState").textContent="Không thể truy cập";alert(e.message)});$("startPractice").onclick=async()=>{sessionAttemptId=`SPK-${test.test_id}-${Date.now()}`;state.started_at=new Date().toISOString();index=0;await saveAttemptProgress("in_progress");render();$("downloadAll").disabled=false;};$("prepareBtn").onclick=()=>countdown(test.tasks[index].preparation_seconds,"Chuẩn bị",()=>startRecording().catch(e=>alert(e.message)));$("recordBtn").onclick=()=>startRecording().catch(e=>alert(e.message));$("stopBtn").onclick=()=>stopRecording().catch(e=>alert(e.message));$("retryBtn").onclick=()=>{state.recordings[test.tasks[index].task_id]=null;render();};$("prevTask").onclick=async()=>{await saveCurrent();if(index>0){index-=1;render();}};$("saveNext").onclick=async()=>{await saveCurrent();if(index<test.tasks.length-1){index+=1;render();}else await finalize();};$("downloadAll").onclick=()=>{const data={schema_version:"2.0.0",bank_release:bank.release?.release_id,attempt_id:sessionAttemptId,test_id:test.test_id,responses:test.tasks.map(t=>({task_id:t.task_id,note:state.notes[t.task_id]||"",recorded:Boolean(state.recordings[t.task_id]),duration_seconds:state.recordings[t.task_id]?.duration_seconds||null,mime_type:state.recordings[t.task_id]?.mime_type||null}))};const a=document.createElement("a");const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.href=url;a.download=`aptis-speaking-${sessionAttemptId}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  window.addEventListener("beforeunload",()=>{clearTimer();media.stopTracks();if(activeUrl)URL.revokeObjectURL(activeUrl);});
  loadTest().then(resume).catch(console.error);
})();
